/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";

import type {
	GetDevtoolsGraphParams,
	GetGraphResponse,
	GetModuleDetailsResponse,
} from "../model";

const withQueryKey = <T extends object, K>(
	query: T,
	queryKey: K,
): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

export const getGetDevtoolsGraphUrl = (params?: GetDevtoolsGraphParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `http://127.0.0.1:3001/__devtools/graph?${stringifiedParams}`
		: `http://127.0.0.1:3001/__devtools/graph`;
};

/**
 * Returns the module dependency graph with optional filtering
 * @summary Get module graph
 */
export const getDevtoolsGraph = async (
	params?: GetDevtoolsGraphParams,
	options?: RequestInit,
): Promise<GetGraphResponse> => {
	const res = await fetch(getGetDevtoolsGraphUrl(params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: GetGraphResponse = body ? JSON.parse(body) : {};
	return data;
};

export const getGetDevtoolsGraphQueryKey = (
	params?: GetDevtoolsGraphParams,
) => {
	return [
		`http://127.0.0.1:3001/__devtools/graph`,
		...(params ? [params] : []),
	] as const;
};

export const getGetDevtoolsGraphQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsGraph>>,
	TError = unknown,
>(
	params?: GetDevtoolsGraphParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraph>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetDevtoolsGraphQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsGraph>>
	> = ({ signal }) => getDevtoolsGraph(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsGraph>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsGraphQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsGraph>>
>;
export type GetDevtoolsGraphQueryError = unknown;

export function useGetDevtoolsGraph<
	TData = Awaited<ReturnType<typeof getDevtoolsGraph>>,
	TError = unknown,
>(
	params: undefined | GetDevtoolsGraphParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraph>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsGraph>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsGraph>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsGraph<
	TData = Awaited<ReturnType<typeof getDevtoolsGraph>>,
	TError = unknown,
>(
	params?: GetDevtoolsGraphParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraph>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsGraph>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsGraph>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsGraph<
	TData = Awaited<ReturnType<typeof getDevtoolsGraph>>,
	TError = unknown,
>(
	params?: GetDevtoolsGraphParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraph>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get module graph
 */

export function useGetDevtoolsGraph<
	TData = Awaited<ReturnType<typeof getDevtoolsGraph>>,
	TError = unknown,
>(
	params?: GetDevtoolsGraphParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraph>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsGraphQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return withQueryKey(query, queryOptions.queryKey);
}

export const getGetDevtoolsGraphSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsGraph>>,
	TError = unknown,
>(
	params?: GetDevtoolsGraphParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraph>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetDevtoolsGraphQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsGraph>>
	> = ({ signal }) => getDevtoolsGraph(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsGraph>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsGraphSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsGraph>>
>;
export type GetDevtoolsGraphSuspenseQueryError = unknown;

export function useGetDevtoolsGraphSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsGraph>>,
	TError = unknown,
>(
	params: undefined | GetDevtoolsGraphParams,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraph>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsGraphSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsGraph>>,
	TError = unknown,
>(
	params?: GetDevtoolsGraphParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraph>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsGraphSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsGraph>>,
	TError = unknown,
>(
	params?: GetDevtoolsGraphParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraph>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get module graph
 */

export function useGetDevtoolsGraphSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsGraph>>,
	TError = unknown,
>(
	params?: GetDevtoolsGraphParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraph>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsGraphSuspenseQueryOptions(params, options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export const getGetDevtoolsGraphModulesModuleIdUrl = (moduleId: string) => {
	return `http://127.0.0.1:3001/__devtools/graph/modules/${moduleId}`;
};

/**
 * Returns detailed information about a specific module
 * @summary Get module details
 */
export const getDevtoolsGraphModulesModuleId = async (
	moduleId: string,
	options?: RequestInit,
): Promise<GetModuleDetailsResponse> => {
	const res = await fetch(getGetDevtoolsGraphModulesModuleIdUrl(moduleId), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: GetModuleDetailsResponse = body ? JSON.parse(body) : {};
	return data;
};

export const getGetDevtoolsGraphModulesModuleIdQueryKey = (
	moduleId: string,
) => {
	return [
		`http://127.0.0.1:3001/__devtools/graph/modules/${moduleId}`,
	] as const;
};

export const getGetDevtoolsGraphModulesModuleIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
	TError = unknown,
>(
	moduleId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetDevtoolsGraphModulesModuleIdQueryKey(moduleId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>
	> = ({ signal }) =>
		getDevtoolsGraphModulesModuleId(moduleId, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: moduleId !== null && moduleId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsGraphModulesModuleIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>
>;
export type GetDevtoolsGraphModulesModuleIdQueryError = unknown;

export function useGetDevtoolsGraphModulesModuleId<
	TData = Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
	TError = unknown,
>(
	moduleId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsGraphModulesModuleId<
	TData = Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
	TError = unknown,
>(
	moduleId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsGraphModulesModuleId<
	TData = Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
	TError = unknown,
>(
	moduleId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get module details
 */

export function useGetDevtoolsGraphModulesModuleId<
	TData = Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
	TError = unknown,
>(
	moduleId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsGraphModulesModuleIdQueryOptions(
		moduleId,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return withQueryKey(query, queryOptions.queryKey);
}

export const getGetDevtoolsGraphModulesModuleIdSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
	TError = unknown,
>(
	moduleId: string,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetDevtoolsGraphModulesModuleIdQueryKey(moduleId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>
	> = ({ signal }) =>
		getDevtoolsGraphModulesModuleId(moduleId, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsGraphModulesModuleIdSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>
>;
export type GetDevtoolsGraphModulesModuleIdSuspenseQueryError = unknown;

export function useGetDevtoolsGraphModulesModuleIdSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
	TError = unknown,
>(
	moduleId: string,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsGraphModulesModuleIdSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
	TError = unknown,
>(
	moduleId: string,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsGraphModulesModuleIdSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
	TError = unknown,
>(
	moduleId: string,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get module details
 */

export function useGetDevtoolsGraphModulesModuleIdSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
	TError = unknown,
>(
	moduleId: string,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsGraphModulesModuleId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsGraphModulesModuleIdSuspenseQueryOptions(
		moduleId,
		options,
	);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
