import type { ModuleGraph } from "./graph.types";

export const sampleGraph: ModuleGraph = {
  rootModuleId: "app-module",
  modules: [
    {
      id: "app-module",
      name: "AppModule",
      kind: "root",
      providers: ["ConfigService", "LoggerService"],
      exports: [],
      controllers: [],
      queryHandlers: [],
      commandHandlers: [],
      queryPreHandlers: [],
      commandPreHandlers: [],
      interceptors: [],
      initializers: [],
    },
    {
      id: "cats-module",
      name: "CatsModule",
      kind: "feature",
      providers: ["catsService", "getCatsService"],
      exports: ["catsService"],
      controllers: ["CatsController", "CatsDecoratedController"],
      queryHandlers: ["GetCatsQueryHandler"],
      commandHandlers: [],
      queryPreHandlers: [],
      commandPreHandlers: [],
      interceptors: ["cache", "retry"],
      initializers: [],
    },
    {
      id: "http-module",
      name: "HttpModule",
      kind: "global",
      providers: ["app", "fastifyService"],
      exports: ["app"],
      controllers: [],
      queryHandlers: [],
      commandHandlers: [],
      queryPreHandlers: [],
      commandPreHandlers: [],
      interceptors: [],
      initializers: ["http"],
    },
    {
      id: "devtools-module",
      name: "DevtoolsModule",
      kind: "internal",
      providers: ["devtoolsOptions", "devtoolsEndpointRegistrar"],
      exports: [],
      controllers: [],
      queryHandlers: [],
      commandHandlers: [],
      queryPreHandlers: [],
      commandPreHandlers: [],
      interceptors: [],
      initializers: [],
    },
  ],
  edges: [
    { from: "app-module", to: "cats-module", type: "imports" },
    { from: "app-module", to: "devtools-module", type: "imports" },
    { from: "app-module", to: "http-module", type: "global" },
    { from: "cats-module", to: "http-module", type: "global" },
  ],
};
