/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";

import type {
	GetDevtoolsPlaygroundMethodsParams,
	GetProviderMethodsResponse,
	InvokeProviderBody,
	InvokeProviderResponse,
} from "../model";

const withQueryKey = <T extends object, K>(
	query: T,
	queryKey: K,
): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

export const getGetDevtoolsPlaygroundMethodsUrl = (
	params: GetDevtoolsPlaygroundMethodsParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `http://127.0.0.1:3001/__devtools/playground/methods?${stringifiedParams}`
		: `http://127.0.0.1:3001/__devtools/playground/methods`;
};

/**
 * Returns available methods for a provider
 * @summary Get provider methods
 */
export const getDevtoolsPlaygroundMethods = async (
	params: GetDevtoolsPlaygroundMethodsParams,
	options?: RequestInit,
): Promise<GetProviderMethodsResponse> => {
	const res = await fetch(getGetDevtoolsPlaygroundMethodsUrl(params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: GetProviderMethodsResponse = body ? JSON.parse(body) : {};
	return data;
};

export const getGetDevtoolsPlaygroundMethodsQueryKey = (
	params?: GetDevtoolsPlaygroundMethodsParams,
) => {
	return [
		`http://127.0.0.1:3001/__devtools/playground/methods`,
		...(params ? [params] : []),
	] as const;
};

export const getGetDevtoolsPlaygroundMethodsQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
	TError = unknown,
>(
	params: GetDevtoolsPlaygroundMethodsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetDevtoolsPlaygroundMethodsQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>
	> = ({ signal }) =>
		getDevtoolsPlaygroundMethods(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsPlaygroundMethodsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>
>;
export type GetDevtoolsPlaygroundMethodsQueryError = unknown;

export function useGetDevtoolsPlaygroundMethods<
	TData = Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
	TError = unknown,
>(
	params: GetDevtoolsPlaygroundMethodsParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsPlaygroundMethods<
	TData = Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
	TError = unknown,
>(
	params: GetDevtoolsPlaygroundMethodsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsPlaygroundMethods<
	TData = Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
	TError = unknown,
>(
	params: GetDevtoolsPlaygroundMethodsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get provider methods
 */

export function useGetDevtoolsPlaygroundMethods<
	TData = Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
	TError = unknown,
>(
	params: GetDevtoolsPlaygroundMethodsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsPlaygroundMethodsQueryOptions(
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return withQueryKey(query, queryOptions.queryKey);
}

export const getGetDevtoolsPlaygroundMethodsSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
	TError = unknown,
>(
	params: GetDevtoolsPlaygroundMethodsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetDevtoolsPlaygroundMethodsQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>
	> = ({ signal }) =>
		getDevtoolsPlaygroundMethods(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsPlaygroundMethodsSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>
>;
export type GetDevtoolsPlaygroundMethodsSuspenseQueryError = unknown;

export function useGetDevtoolsPlaygroundMethodsSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
	TError = unknown,
>(
	params: GetDevtoolsPlaygroundMethodsParams,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsPlaygroundMethodsSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
	TError = unknown,
>(
	params: GetDevtoolsPlaygroundMethodsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsPlaygroundMethodsSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
	TError = unknown,
>(
	params: GetDevtoolsPlaygroundMethodsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get provider methods
 */

export function useGetDevtoolsPlaygroundMethodsSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
	TError = unknown,
>(
	params: GetDevtoolsPlaygroundMethodsParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsPlaygroundMethods>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsPlaygroundMethodsSuspenseQueryOptions(
		params,
		options,
	);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export const getPostDevtoolsPlaygroundInvokeUrl = () => {
	return `http://127.0.0.1:3001/__devtools/playground/invoke`;
};

/**
 * Invokes a method on a provider and returns the result
 * @summary Invoke provider method
 */
export const postDevtoolsPlaygroundInvoke = async (
	invokeProviderBody: InvokeProviderBody,
	options?: RequestInit,
): Promise<InvokeProviderResponse> => {
	const res = await fetch(getPostDevtoolsPlaygroundInvokeUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(invokeProviderBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: InvokeProviderResponse = body ? JSON.parse(body) : {};
	return data;
};

export const getPostDevtoolsPlaygroundInvokeMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postDevtoolsPlaygroundInvoke>>,
		TError,
		{ data: InvokeProviderBody },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postDevtoolsPlaygroundInvoke>>,
	TError,
	{ data: InvokeProviderBody },
	TContext
> => {
	const mutationKey = ["postDevtoolsPlaygroundInvoke"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postDevtoolsPlaygroundInvoke>>,
		{ data: InvokeProviderBody }
	> = (props) => {
		const { data } = props ?? {};

		return postDevtoolsPlaygroundInvoke(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostDevtoolsPlaygroundInvokeMutationResult = NonNullable<
	Awaited<ReturnType<typeof postDevtoolsPlaygroundInvoke>>
>;
export type PostDevtoolsPlaygroundInvokeMutationBody = InvokeProviderBody;
export type PostDevtoolsPlaygroundInvokeMutationError = unknown;

/**
 * @summary Invoke provider method
 */
export const usePostDevtoolsPlaygroundInvoke = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postDevtoolsPlaygroundInvoke>>,
			TError,
			{ data: InvokeProviderBody },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postDevtoolsPlaygroundInvoke>>,
	TError,
	{ data: InvokeProviderBody },
	TContext
> => {
	return useMutation(
		getPostDevtoolsPlaygroundInvokeMutationOptions(options),
		queryClient,
	);
};
