/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */

export const ConsoleEntryLevel = {
	log: "log",
	info: "info",
	warn: "warn",
	error: "error",
} as const;
export type ConsoleEntryLevel =
	(typeof ConsoleEntryLevel)[keyof typeof ConsoleEntryLevel];
