/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */
import type { ProviderImpactItem } from "./providerImpactItem";

export interface GetProviderImpactResponse {
	changedFiles: string[];
	newFiles: string[];
	deletedFiles: string[];
	changedProviders: ProviderImpactItem[];
	deletedProviders: ProviderImpactItem[];
	newProviders: ProviderImpactItem[];
	affectedProviders: ProviderImpactItem[];
}
