/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */
import type { ConsoleEntry } from "./consoleEntry";
import type { InvokeError } from "./invokeError";

export interface InvokeProviderResponse {
	ok: boolean;
	result?: unknown;
	error?: InvokeError;
	console: ConsoleEntry[];
}
