/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */

export const LifetimeType = {
	SINGLETON: "SINGLETON",
	SCOPED: "SCOPED",
	TRANSIENT: "TRANSIENT",
} as const;
export type LifetimeType = (typeof LifetimeType)[keyof typeof LifetimeType];
