/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */

export const ModuleGraphNodeKind = {
	root: "root",
	global: "global",
	feature: "feature",
} as const;
export type ModuleGraphNodeKind =
	(typeof ModuleGraphNodeKind)[keyof typeof ModuleGraphNodeKind];
