/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */
import type { RouteSchema } from "./routeSchema";

export interface ModuleGraphRoute {
	method: string;
	path: string;
	controller: string;
	handler: string;
	schema?: RouteSchema;
}
