/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */
import type { ConsoleEntry } from "./consoleEntry";
import type { TraceSpanError } from "./traceSpanError";
import type { TraceSpanKind } from "./traceSpanKind";
import type { TraceSpanStatus } from "./traceSpanStatus";

export interface TraceSpan {
	id: string;
	/** @nullable */
	parentId: string | null;
	kind: TraceSpanKind;
	label: string;
	/** @nullable */
	moduleId: string | null;
	/** @nullable */
	moduleName: string | null;
	/** @nullable */
	providerKey: string | null;
	methodName: string;
	args: unknown[];
	result: unknown;
	/** @nullable */
	error: TraceSpanError;
	startedAt: number;
	durationMs: number;
	status: TraceSpanStatus;
	console: ConsoleEntry[];
}
