/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */

export const TraceSpanKind = {
	controller: "controller",
	handler: "handler",
	interceptor: "interceptor",
	mediator: "mediator",
	prehandler: "prehandler",
	provider: "provider",
} as const;
export type TraceSpanKind = (typeof TraceSpanKind)[keyof typeof TraceSpanKind];
